create table if not exists public.unique_total_stats (
  id bigint generated by default as identity primary key,
  totals jsonb not null,
  date date not null
);

create index if not exists idx_unique_total_stats_date
  on public.unique_total_stats (date);
