create table if not exists public.device_manufacturer_stats (
  id bigint generated by default as identity primary key,
  device_id varchar not null references public.devices(device),
  manufacturer_data jsonb not null,
  date date not null
);

create index if not exists idx_device_manufacturer_stats_device_id
  on public.device_manufacturer_stats (device_id);

create index if not exists idx_device_manufacturer_stats_date
  on public.device_manufacturer_stats (date);
