create table if not exists public.mac_stats (
  id bigint generated by default as identity primary key,
  mac varchar not null,
  seen_count bigint not null,
  first_seen timestamp without time zone not null,
  last_seen timestamp without time zone not null
);

create unique index if not exists uq_mac_stats_mac
  on public.mac_stats (mac);

create index if not exists idx_mac_stats_first_seen
  on public.mac_stats (first_seen);

create index if not exists idx_mac_stats_last_seen
  on public.mac_stats (last_seen);
