create table if not exists public.daily_imports_mac (
  id bigint generated by default as identity primary key,
  count bigint not null,
  date date not null
);

create unique index if not exists uq_daily_imports_mac_date
  on public.daily_imports_mac (date);

create table if not exists public.daily_imports_ssid (
  id bigint generated by default as identity primary key,
  count bigint not null,
  date date not null
);

create unique index if not exists uq_daily_imports_ssid_date
  on public.daily_imports_ssid (date);

create table if not exists public.daily_imports_probes (
  id bigint generated by default as identity primary key,
  count bigint not null,
  date date not null
);

create unique index if not exists uq_daily_imports_probes_date
  on public.daily_imports_probes (date);