create table if not exists public.device_daily_imports (
  id bigint generated by default as identity primary key,
  device_id varchar not null references public.devices(device),
  ssid bigint not null,
  mac bigint not null,
  probes bigint not null,
  date date not null
);

create index if not exists idx_device_daily_imports_device_id
  on public.device_daily_imports (device_id);

create index if not exists idx_device_daily_imports_date
  on public.device_daily_imports (date);

create unique index if not exists uq_device_daily_imports_device_date
  on public.device_daily_imports (device_id, date);
