create table if not exists public.manufacturer_stats (
  id bigint generated by default as identity primary key,
  company varchar not null,
  country varchar null,
  country_alpha3 varchar(3) null,
  total_occurrences integer not null,
  percentage double precision not null
);

create index if not exists idx_manufacturer_stats_company
  on public.manufacturer_stats (company);

create unique index if not exists uq_manufacturer_stats_company_country_alpha3
  on public.manufacturer_stats (company, country, country_alpha3);
