create table if not exists public.ssid_stats (
  id bigint generated by default as identity primary key,
  ssid varchar not null,
  seen_count bigint not null,
  first_seen timestamp without time zone not null,
  last_seen timestamp without time zone not null
);

create unique index if not exists uq_ssid_stats_ssid
  on public.ssid_stats (ssid);

create index if not exists idx_ssid_stats_first_seen
  on public.ssid_stats (first_seen);

create index if not exists idx_ssid_stats_last_seen
  on public.ssid_stats (last_seen);
