repos:
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort (python imports)
        args: ["--profile", "black"]
        files: ^(aggregator|collector|firebase_housekeeping|tests|util|collector_metrics_agent|orchestrator|stats|stats_api)/
        types: [python]

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        name: black (python formatter)
        files: ^(aggregator|collector|firebase_housekeeping|tests|util|collector_metrics_agent|orchestrator|stats|stats_api)/
        types: [python]
