query($accountTag: string!, $datetimeStart: Time!, $datetimeEnd: Time!, $limit: uint64!, $bucketName: string!) {
  viewer {
    accounts(filter: {accountTag: $accountTag}) {
      r2OperationsAdaptiveGroups(
        limit: $limit
        filter: {
          datetime_geq: $datetimeStart,
          datetime_leq: $datetimeEnd,
          bucketName: $bucketName
        }
      ) {
        dimensions {
          actionType
        }
        sum {
          requests
        }
      }
    }
  }
}
