[project]
name = "stats-api"
version = "0.1.0"
description = "Stats API service"
requires-python = ">=3.11"

dependencies = [
    "SQLAlchemy==2.0.50",
    "python-dotenv==1.2.1",
    "psycopg2-binary==2.9.11",
    "fastapi[standard]==0.135.1",
    "uvicorn==0.41.0",
    "sentry-sdk==2.48.0",
    "firebase-admin==7.1.0",
    "redis==8.0.1",
    "fastapi-cache2==0.2.2",
    "tenacity==9.1.2",
    "logfire[fastapi,sqlalchemy,redis]==4.37.0",
]

[tool.fastapi]
entrypoint = "main:app"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = [
    "core*",
    "routers*",
    "middleware*",
]