services:
  ssid_geo_mapper:
    build:
      context: ..
      dockerfile: ssid_geo_mapper/Dockerfile
    container_name: ssid_geo_mapper
    env_file:
      - ./.env
    environment:
      SERVER_URL: 0.0.0.0
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    networks:
      - pnls

networks:
  pnls:
    name: pnls
    driver: bridge
