services:
  aggregator:
    build:
      context: ..
      dockerfile: aggregator/Dockerfile
    container_name: aggregator
    networks:
      - pnls
    env_file:
      - ./.env
    environment:
      SERVER_URL: 0.0.0.0
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  aggregator_worker:
    build:
      context: ..
      dockerfile: aggregator/Dockerfile
    container_name: aggregator_worker
    networks:
      - pnls
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: celery -A aggregator.background.celery:celery worker -E --loglevel=info
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - pnls
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pnls:/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 1s
      timeout: 10s
      retries: 50

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    networks:
      - pnls
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - "5050:80"
    volumes:
      - pnls:/data/pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:8.8.0
    container_name: redis
    networks:
      - pnls
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 10s
      retries: 20

  redisinsight:
    image: redis/redisinsight:3.6
    container_name: redisinsight
    networks:
      - pnls
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    volumes:
      - redisinsight_data:/data
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy

  flower:
    build:
      context: ..
      dockerfile: aggregator/Dockerfile
    container_name: flower
    networks:
      - pnls
    env_file:
      - ./.env
    ports:
      - "${FLOWER_PORT}:5555"
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A aggregator.background.celery:celery flower --port=5555
    restart: unless-stopped

volumes:
  pnls:
  redis_data:
  redisinsight_data:

networks:
  pnls:
    name: pnls
    driver: bridge