name: Go Code Style Check

on:
  push:
    branches: [master]
    paths:
      - "**/*.go"
  pull_request:
    branches: [master]
    paths:
      - "**/*.go"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Run golangci-lint fmt check (collector_status_notifier)
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          working-directory: collector_status_notifier
          args: fmt --check

      - name: Run golangci-lint fmt check (firebase_limit_notifier)
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          working-directory: firebase_limit_notifier
          args: fmt --check
