name: Go Code Style Check

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.go'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.go'

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'

      - name: Install gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt check
        run: |
          gofumpt -l -d collector_status_notifier/
