name: Go Code Style Check

on:
  push:
    branches: [master]
    paths:
      - "**/*.go"
  pull_request:
    branches: [master]
    paths:
      - "**/*.go"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Run golangci-lint fmt check (collector_status_notifier)
        run: |
          cd collector_status_notifier
          golangci-lint fmt
          git diff --exit-code

      - name: Run golangci-lint fmt check (firebase_limit_notifier)
        run: |
          cd firebase_limit_notifier
          golangci-lint fmt
          git diff --exit-code

      - name: Run golangci-lint fmt check (util-go)
        run: |
          cd util-go
          golangci-lint fmt
          git diff --exit-code

      - name: Run golangci-lint fmt check (db_backup)
        run: |
          cd db_backup
          golangci-lint fmt
          git diff --exit-code

      - name: Run golangci-lint fmt check (cloudflare_limit_notifier)
        run: |
          cd cloudflare_limit_notifier
          golangci-lint fmt
          git diff --exit-code
