name: PNLS-DC Go Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'collector_status_notifier/**/*.go'
      - 'collector_status_notifier/go.mod'
      - 'collector_status_notifier/go.sum'
  pull_request:
    branches: [ master ]
    paths:
      - 'collector_status_notifier/**/*.go'
      - 'collector_status_notifier/go.mod'
      - 'collector_status_notifier/go.sum'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.5'

    - name: Install dependencies
      run: |
        cd collector_status_notifier
        go mod tidy

    - name: Run tests
      run: |
        cd collector_status_notifier
        go test -v
